//! # Chronos Core Runtime
//!
//! This crate defines the canonical runtime objects for the Chronos Personal Context Operating System.
//! It serves as the foundational data contract for the entire architecture. No business logic
//! exists here; this crate exists strictly to define the `Chronos Object Model (COM)`.
//!
//! ## Objects
//! - `ChronosEvent`: The fundamental unit of perception.
//! - `ChronosState`: The aggregated world model.
//! - `ChronosIntent`: The inferred objective (Goal or Session).
//! - `ChronosDecision`: A formal resolution to intervene.
//! - `ChronosAction`: An executable command.
//! - `ChronosReflection`: The learning record.
//! - `ChronosCapability`: System capabilities, permissions, and health.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Returns the current stable schema version for all objects.
pub const CURRENT_SCHEMA_VERSION: &str = "1.0";

/// Generates a stable unique identifier.
fn generate_id() -> String {
    Uuid::new_v4().to_string()
}

/// # ChronosEvent
/// The fundamental unit of perception. The raw recording of reality.
/// Generated by the Perception Layer (Adapters).
/// Immutable, replayable, and strictly factual.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosEvent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub event_type: String,
    pub source: String,
    pub payload: serde_json::Value,
}

impl ChronosEvent {
    /// Constructs a new `ChronosEvent`.
    pub fn new(event_type: impl Into<String>, source: impl Into<String>, payload: serde_json::Value) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            event_type: event_type.into(),
            source: source.into(),
            payload,
        }
    }

    /// Constructs a `ChronosEvent` preserving original provenance (ID and Timestamp).
    pub fn new_with_provenance(
        id: impl Into<String>,
        timestamp: DateTime<Utc>,
        event_type: impl Into<String>,
        source: impl Into<String>,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            id: id.into(),
            timestamp,
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            event_type: event_type.into(),
            source: source.into(),
            payload,
        }
    }
}

/// # ChronosState
/// The aggregated world model representing the ground truth at any millisecond.
/// Maintained by the Memory Layer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosState {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub active_intents: Vec<String>,
    pub active_capabilities: Vec<String>,
    pub payload: serde_json::Value,
}

impl ChronosState {
    /// Constructs a new `ChronosState`.
    pub fn new(active_intents: Vec<String>, active_capabilities: Vec<String>, payload: serde_json::Value) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            active_intents,
            active_capabilities,
            payload,
        }
    }
}

/// The classification of an intent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum IntentType {
    /// Long-lived, overarching objectives.
    Goal,
    /// Ephemeral, immediate objectives bound to a Cognitive Session.
    Session,
}

/// The current state of an intent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum IntentStatus {
    Active,
    Paused,
    Completed,
    Abandoned,
}

/// # ChronosIntent
/// The inferred objective the user is pursuing. The center of the semantic graph.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosIntent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub intent_type: IntentType,
    pub description: String,
    pub status: IntentStatus,
    pub confidence: u8,
    pub parent_concepts: Vec<String>,
}

impl ChronosIntent {
    /// Constructs a new `ChronosIntent`.
    pub fn new(
        intent_type: IntentType,
        description: impl Into<String>,
        confidence: u8,
        parent_concepts: Vec<String>,
    ) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            intent_type,
            description: description.into(),
            status: IntentStatus::Active,
            confidence,
            parent_concepts,
        }
    }
}

/// # ChronosDecision
/// A formal resolution to intervene or modify the system, created by the Decision Orchestrator.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosDecision {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub confidence: u8,
    pub explanation: String,
    pub evidence_ids: Vec<String>,
    pub action_type: String,
    pub action_payload: serde_json::Value,
    pub expires_at: Option<DateTime<Utc>>,
}

impl ChronosDecision {
    /// Constructs a new `ChronosDecision`.
    pub fn new(
        confidence: u8,
        explanation: impl Into<String>,
        evidence_ids: Vec<String>,
        action_type: impl Into<String>,
        action_payload: serde_json::Value,
        expires_at: Option<DateTime<Utc>>,
    ) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            confidence,
            explanation: explanation.into(),
            evidence_ids,
            action_type: action_type.into(),
            action_payload,
            expires_at,
        }
    }
}

/// The execution state of an action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActionStatus {
    Pending,
    Authorized,
    Executing,
    Success,
    Failed,
}

/// # ChronosAction
/// An executable command translating a Decision into a physical change.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosAction {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub decision_id: String,
    pub status: ActionStatus,
    pub action_type: String,
    pub payload: serde_json::Value,
}

impl ChronosAction {
    /// Constructs a new `ChronosAction` based on a decision.
    pub fn new(decision_id: impl Into<String>, action_type: impl Into<String>, payload: serde_json::Value) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            decision_id: decision_id.into(),
            status: ActionStatus::Pending,
            action_type: action_type.into(),
            payload,
        }
    }
}

/// # ChronosReflection
/// The learning record generated after an Action or Decision concludes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosReflection {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub related_action_id: Option<String>,
    pub related_decision_id: Option<String>,
    pub outcome_evaluation: String,
    pub confidence_delta: i8,
}

impl ChronosReflection {
    /// Constructs a new `ChronosReflection`.
    pub fn new(
        related_action_id: Option<String>,
        related_decision_id: Option<String>,
        outcome_evaluation: impl Into<String>,
        confidence_delta: i8,
    ) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            related_action_id,
            related_decision_id,
            outcome_evaluation: outcome_evaluation.into(),
            confidence_delta,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CapabilityStatus {
    Enabled,
    Disabled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CapabilityHealth {
    Healthy,
    Degraded,
    Failing,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CapabilityPermission {
    Granted,
    Denied,
}

/// # ChronosCapability
/// A first-class object representing what the system is currently able to do.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChronosCapability {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub name: String,
    pub status: CapabilityStatus,
    pub health: CapabilityHealth,
    pub permission: CapabilityPermission,
    pub properties: serde_json::Value,
}

impl ChronosCapability {
    /// Constructs a new `ChronosCapability`.
    pub fn new(
        name: impl Into<String>,
        status: CapabilityStatus,
        health: CapabilityHealth,
        permission: CapabilityPermission,
        properties: serde_json::Value,
    ) -> Self {
        Self {
            id: generate_id(),
            timestamp: Utc::now(),
            schema_version: CURRENT_SCHEMA_VERSION.to_string(),
            name: name.into(),
            status,
            health,
            permission,
            properties,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_chronos_event_serialization() {
        let event = ChronosEvent::new(
            "ClipboardCopied",
            "User",
            json!({"text": "print('hello')"}),
        );
        let serialized = serde_json::to_string(&event).unwrap();
        let deserialized: ChronosEvent = serde_json::from_str(&serialized).unwrap();
        assert_eq!(event, deserialized);
        assert_eq!(deserialized.schema_version, "1.0");
    }

    #[test]
    fn test_chronos_intent_serialization() {
        let intent = ChronosIntent::new(
            IntentType::Session,
            "Implement Core Runtime",
            95,
            vec!["Rust".to_string(), "Architecture".to_string()],
        );
        let serialized = serde_json::to_string(&intent).unwrap();
        let deserialized: ChronosIntent = serde_json::from_str(&serialized).unwrap();
        assert_eq!(intent, deserialized);
        assert_eq!(deserialized.status, IntentStatus::Active);
    }

    #[test]
    fn test_chronos_capability_serialization() {
        let cap = ChronosCapability::new(
            "GitAdapter",
            CapabilityStatus::Enabled,
            CapabilityHealth::Healthy,
            CapabilityPermission::Granted,
            json!({"version": "2.40.1"}),
        );
        let serialized = serde_json::to_string(&cap).unwrap();
        let deserialized: ChronosCapability = serde_json::from_str(&serialized).unwrap();
        assert_eq!(cap, deserialized);
    }

    #[test]
    fn test_chronos_decision_and_action() {
        let decision = ChronosDecision::new(
            80,
            "Detected completion intent",
            vec!["evt_123".to_string()],
            "NotifyUser",
            json!({"message": "Good job"}),
            None,
        );
        let serialized_dec = serde_json::to_string(&decision).unwrap();
        let deserialized_dec: ChronosDecision = serde_json::from_str(&serialized_dec).unwrap();
        assert_eq!(decision, deserialized_dec);

        let action = ChronosAction::new(
            decision.id.clone(),
            decision.action_type.clone(),
            decision.action_payload.clone(),
        );
        let serialized_act = serde_json::to_string(&action).unwrap();
        let deserialized_act: ChronosAction = serde_json::from_str(&serialized_act).unwrap();
        assert_eq!(action, deserialized_act);
        assert_eq!(action.status, ActionStatus::Pending);
    }

    #[test]
    fn test_chronos_reflection_serialization() {
        let reflection = ChronosReflection::new(
            Some("act_123".to_string()),
            Some("dec_123".to_string()),
            "User accepted recommendation",
            5,
        );
        let serialized = serde_json::to_string(&reflection).unwrap();
        let deserialized: ChronosReflection = serde_json::from_str(&serialized).unwrap();
        assert_eq!(reflection, deserialized);
    }

    #[test]
    fn test_chronos_state_serialization() {
        let state = ChronosState::new(
            vec!["intent_1".to_string()],
            vec!["cap_1".to_string()],
            json!({"environment": "development"}),
        );
        let serialized = serde_json::to_string(&state).unwrap();
        let deserialized: ChronosState = serde_json::from_str(&serialized).unwrap();
        assert_eq!(state, deserialized);
    }
}
